apiVersion: operator.cert-manager.io/v1alpha1
kind: OperatorConfig
metadata:
  name: operatorconfig-sample
spec:
  # Default values copied from <project_dir>/helm-charts/cert-manager/values.yaml
  affinity: {}
  cainjector:
    affinity: {}
    containerSecurityContext: {}
    enabled: true
    extraArgs: []
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/jetstack/cert-manager-cainjector
    nodeSelector: {}
    podLabels: {}
    replicaCount: 1
    resources: {}
    securityContext:
      runAsNonRoot: true
    serviceAccount:
      automountServiceAccountToken: true
      create: true
    strategy: {}
    tolerations: []
  clusterResourceNamespace: ""
  containerSecurityContext: {}
  extraArgs: []
  extraEnv: []
  featureGates: ""
  global:
    imagePullSecrets: []
    leaderElection:
      namespace: kube-system
    logLevel: 2
    podSecurityPolicy:
      enabled: false
      useAppArmor: true
    priorityClassName: ""
    rbac:
      create: true
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/jetstack/cert-manager-controller
  ingressShim: {}
  installCRDs: false
  nodeSelector: {}
  podLabels: {}
  prometheus:
    enabled: true
    servicemonitor:
      enabled: false
      honorLabels: false
      interval: 60s
      labels: {}
      path: /metrics
      prometheusInstance: default
      scrapeTimeout: 30s
      targetPort: 9402
  replicaCount: 1
  resources: {}
  securityContext:
    runAsNonRoot: true
  serviceAccount:
    automountServiceAccountToken: true
    create: true
  startupapicheck:
    affinity: {}
    backoffLimit: 4
    enabled: true
    extraArgs: []
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/jetstack/cert-manager-ctl
    jobAnnotations:
      helm.sh/hook: post-install
      helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
      helm.sh/hook-weight: "1"
    nodeSelector: {}
    podLabels: {}
    rbac:
      annotations:
        helm.sh/hook: post-install
        helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
        helm.sh/hook-weight: "-5"
    resources: {}
    securityContext:
      runAsNonRoot: true
    serviceAccount:
      annotations:
        helm.sh/hook: post-install
        helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
        helm.sh/hook-weight: "-5"
      automountServiceAccountToken: true
      create: true
    timeout: 1m
    tolerations: []
  strategy: {}
  tolerations: []
  volumeMounts: []
  volumes: []
  webhook:
    affinity: {}
    config: null
    containerSecurityContext: {}
    extraArgs: []
    hostNetwork: false
    image:
      pullPolicy: IfNotPresent
      repository: quay.io/jetstack/cert-manager-webhook
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    nodeSelector: {}
    podLabels: {}
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    replicaCount: 1
    resources: {}
    securePort: 10250
    securityContext:
      runAsNonRoot: true
    serviceAccount:
      automountServiceAccountToken: true
      create: true
    serviceLabels: {}
    serviceType: ClusterIP
    strategy: {}
    timeoutSeconds: 10
    tolerations: []
    url: {}
  
  
